type: "orchestration"
version: "1.0"
pipeline:
  components:
    Start:
      type: "start"
      transitions:
        unconditional:
        - "Create Table"
      parameters:
        componentName: "Start"
    Create Table:
      type: "create-table-v2"
      parameters:
        componentName: "Create Table"
        createMethod: "Create If Not Exists"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        table: "CUSTOMER"
        snowflakeTableType: "Permanent"
        columns:
        - - "CustomerID"
          - "NUMBER"
          - ""
          - ""
          - ""
          - "No"
          - "No"
          - ""
          - ""
        - - "LastName "
          - "VARCHAR"
          - "60"
          - ""
          - ""
          - "No"
          - "No"
          - ""
          - ""
        - - "FirstName "
          - "VARCHAR"
          - "60"
          - ""
          - ""
          - "No"
          - "No"
          - ""
          - ""
        - - "BirthDate "
          - "VARCHAR"
          - "20"
          - ""
          - ""
          - "No"
          - "No"
          - ""
          - ""
        - - "Gender "
          - "VARCHAR"
          - "20"
          - ""
          - ""
          - "No"
          - "No"
          - ""
          - ""
        - - "ParticipantType"
          - "VARCHAR"
          - "20"
          - ""
          - ""
          - "No"
          - "No"
          - ""
          - ""
        - - "RegionID"
          - "NUMBER"
          - ""
          - ""
          - ""
          - "No"
          - "No"
          - ""
          - ""
        - - "MaritalStatus "
          - "VARCHAR"
          - "15"
          - ""
          - ""
          - "No"
          - "No"
          - ""
          - ""
        defaultDdlCollation:
        primaryKeys:
        clusteringKeys:
        dataRetentionTimeInDays:
        comment:
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
design:
  components:
    Start:
      position:
        x: 0
        "y": 0
      tempMetlId: 1
    Create Table:
      position:
        x: 160
        "y": 0
      tempMetlId: 2
